CREATE DATABASE IF NOT EXISTS ShopDB;
USE ShopDB;

CREATE TABLE Countries (
    ID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE GeoIPCache (
    ID INT NOT NULL,
    IPRange VARCHAR(50) NOT NULL,
    CountryID INT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=Memory;

CREATE TABLE ProductDescription (
    ID INT NOT NULL,
    Description VARCHAR(100) NOT NULL,
    ProductID INT NOT NULL,
    CountryID INT NOT NULL
) ENGINE=MyISAM;

CREATE TABLE Logs (
    ID INT NOT NULL,
    Timestamp DATE NOT NULL,
    Message VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=BLACKHOLE;

CREATE TABLE ProductReporting (
    Date DATE NOT NULL,
    ProductName VARCHAR(50) NOT NULL,
    Orders VARCHAR(100) NOT NULL
) ENGINE=CSV;
